name: API Server
on:
  push:
    paths:
      - .github/workflows/measure-go.yml
      - measure-backend/measure-go/dockerfile
      - measure-backend/measure-go/**/*.go
      - measure-backend/measure-go/**/*.mod
      - measure-backend/measure-go/**/*.sum
  pull_request:
    paths:
      - measure-backend/measure-go/**/*.go
      - measure-backend/measure-go/**/*.mod
      - measure-backend/measure-go/**/*.sum

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: measure-sh/measure-go

jobs:
  build:
    name: Build API server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.x"]
    defaults:
      run:
        working-directory: measure-backend/measure-go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache-dependency-path: measure-backend/measure-go/go.sum
      - name: Display go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Build with ${{ matrix.go-version }}
        run: go build -v ./...

  test:
    name: Test API server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.x"]
    defaults:
      run:
        working-directory: measure-backend/measure-go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache-dependency-path: measure-backend/measure-go/go.sum
      - name: Display go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Test with ${{ matrix.go-version }}
        run: go test ./...
  
  push:
    name: Build Docker image
    runs-on: ubuntu-latest
    #if: github.ref_type == 'tag'
    needs: [build, test]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: measure-backend/measure-go/dockerfile
          push: true
          tags: meausre-sh/measure-go:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.source=https://github.com/measure-sh/measure/tree/${{ github.ref_name }}/measure-backend/measure-go/dockerfile
            org.opencontainers.image.description="Measure API Server"
            org.opencontainers.image.licenses="Apache-2.0"
          # build-args: |
          #   IMAGE_REF=${{ github.ref_name }}
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

      # Disable artifact attestation till repo is public
      # as this is a paid feature in GitHub.
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true

  deploy:
    name: Deploy API server
    if: github.ref == 'refs/heads/main'
    needs: [build, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: measure-backend/measure-go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
