name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release-notes:
    name: Generate release notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          token: ${{ secrets.CHANGELOG_PUSH_TOKEN }}

      - name: Generate changelog using git-cliff
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose --bump
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit the changelog
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "ci: update changelog"
          git push

      - name: Generate release notes
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --github-repo ${{ github.repository }} --current --strip header footer

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: ${{ contains(github.ref_name, '-') }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title Release ${{ github.ref_name }} \
            --draft false \
            --prerelease ${{ env.PRERELEASE }} \
            --latest false \
            --notes "${{ steps.git-cliff.outputs.content }}" \
            --verify-tag